service: quotes
provider:
 name: aws
 runtime: python3.8
 region: ap-south-1
 memorySize: 128
plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
 wsgi:
   app: app.app
   packRequirements: false
package:
  exclude:
    - node_modules/**
    - venv/**
functions:
 app:
   handler: wsgi_handler.handler
   events:
     - http: ANY /
     - http: 'ANY {proxy+}'
